apiversion: modelslim_v1
metadata:
  config_id: deepseek_v4_flash_w8a8
  score: 90
  verified_model_types:
    - DeepSeek-V4-Flash
  verified_tags:
    DeepSeek-V4-Flash:
      - - vLLM-Ascend
        - Atlas_A3_Inference
  label:
    w_bit: 8
    a_bit: 8
    is_sparse: False
    kv_cache: False

default_w8a8_dynamic: &default_w8a8_dynamic
  act:
    scope: "per_token"
    dtype: "int8"
    symmetric: True
    method: "minmax"
  weight:
    scope: "per_channel"
    dtype: "int8"
    symmetric: True
    method: "minmax"

spec:
  process:
    # quaRot/smoothQuant are not executed in this script
    - type: "linear_quant"
      qconfig: *default_w8a8_dynamic
      include:
        - "*attn*"
      exclude:
        - "*attn.wq_a"
        - "*attn.wkv"
        - "*attn.wo_a"
        - "*weights_proj"
        - "*compressor.wgate"
        - "*compressor.wkv"
        - "*indexer.wkv"
        - "*indexer.wgate"
        - "*indexer.weights_proj"
        - "*indexer.compressor.wgate"
        - "*indexer.compressor.wkv"
    - type: "linear_quant"
      qconfig: *default_w8a8_dynamic
      include:
        - "*ffn*"
      exclude:
        - "*gate"
    # MTP-specific projections
    - type: "linear_quant"
      qconfig: *default_w8a8_dynamic
      include:
        - "*e_proj"
        - "*h_proj"
  save:
    - type: "ascendv1_saver"
      part_file_size: 4
